reg:
    path: /reg
    controller: App\Controller\SiteController::reg
login:
    path: /login
    controller: App\Controller\SiteController::login
mainPage:
    path: /
    controller: App\Controller\SiteController::index
logout:
    path: /logout
    controller: App\Controller\SiteController::logout
userCab:
    path: /userCab
    controller: App\Controller\SiteController::userCab
